text:
  max_text_to_height_ratio: 0.3
  margins:
    vertical: 10
    horizontal: 10
  font:
    name: Anton-Regular
    extension: ttf
    search_paths: 
      - ../optional/path/to/your/fonts 
images:
  templates:
    extensions:
      - png
      - jpg
      - jpeg
    search_paths:
      - ../optional/path/to/your/pictures 
  remote:
    timeout: 10
    verify_ssl: true
interface:
  typer:
    no_arg_is_help: true