templates:
  - name: Ancient Aliens
    url: https://imgflip.com/s/meme/Ancient-Aliens.jpg
  - name: Star Wars Yoda
    url: https://imgflip.com/s/meme/Star-Wars-Yoda.jpg
  - name: Distracted Boyfriend
    url: https://imgflip.com/s/meme/Distracted-Boyfriend.jpg
  - name: Drake Hotline Bling
    url: https://imgflip.com/s/meme/Drake-Hotline-Bling.jpg
  - name: Two Buttons
    url: https://imgflip.com/s/meme/Two-Buttons.jpg
  - name: Change My Mind
    url: https://imgflip.com/s/meme/Change-My-Mind.jpg
  - name: Is This a Pigeon
    url: https://imgflip.com/s/meme/Is-This-A-Pigeon.jpg
  - name: The Rock Driving
    url: https://imgflip.com/s/meme/The-Rock-Driving.jpg
  - name: Roll Safe
    url: https://imgflip.com/s/meme/Roll-Safe-Think-About-It.jpg
  - name: Grus Plan
    url: https://imgflip.com/s/meme/Grus-Plan.jpg
  - name: Arthur Fist
    url: https://imgflip.com/s/meme/Arthur-Fist.jpg
  - name: This Is Fine
    url: https://imgflip.com/s/meme/This-Is-Fine.jpg
  - name: Bernie Once Again
    url: https://i.imgflip.com/3orr9x.jpg
  - name: Hide the Pain Harold
    url: https://imgflip.com/s/meme/Hide-the-Pain-Harold.jpg
  - name: Doge
    url: https://imgflip.com/s/meme/Doge.jpg
  - name: Surprised Pikachu
    url: https://imgflip.com/s/meme/Surprised-Pikachu.jpg
  - name: Spongebob Ight Imma Head Out
    url: https://imgflip.com/s/meme/Spongebob-Ight-Imma-Head-Out.jpg
  - name: Grumpy Cat
    url: https://imgflip.com/s/meme/Grumpy-Cat.jpg
  - name: Miley Cyrus Wrecking Ball
    url: https://imgflip.com/s/meme/Miley-Cyrus-Wrecking-Ball.jpg
  - name: First World Problems
    url: https://imgflip.com/s/meme/First-World-Problems.jpg
  - name: Scumbag Steve
    url: https://imgflip.com/s/meme/Scumbag-Steve.jpg
  - name: Philosoraptor
    url: https://imgflip.com/s/meme/Philosoraptor.jpg
  - name: Overly Attached Girlfriend
    url: https://imgflip.com/s/meme/Overly-Attached-Girlfriend.jpg
  - name: Left Exit 12 Off Ramp
    url: https://imgflip.com/s/meme/Left-Exit-12-Off-Ramp.jpg
  - name: Running Away Balloon
    url: https://imgflip.com/s/meme/Running-Away-Balloon.jpg
  - name: This little maneuver
    url: https://i.imgflip.com/82u3gx.jpg
# TODO(Kryzsztof): fix broken links (although they will be a nice display for a demo!) :)